### PR TITLE
Updated contributor list

### PR DESCRIPTION
**Pull request by girishla**

### CODE REVIEW

**Comment by mirceaalexandru** [comment]
@girishla I think Dean wanted to say to add yourself as contributor to seneca-auth

**Comment by girishla** [comment]
oh sorry, I'll close this.

**Comment by mcdonnelldean** [comment]
@girishla Yup, our rule is for any reasonable PR accepted you get added to the list on the project it was accepted :D

**Comment by girishla** [comment]
That's cool, I hope you don't mind me creating another PR for that on seneca-auth then :wink:

**Comment by mcdonnelldean** [comment]
@girishla Not at all, go for it

**Pull request closed without merging**
